src/PG_Portal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from app.views import (login_view, register_view, logout_view, 
    booking_view, booking_success, contact_us, 
    review_create, booking_detail, check_availibility, 
    gallery, booking_detail, about, 
    blog, faq, room_detail, room_detail1, 
    room_detail2, room_detail3, payment_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^check_availibility/', check_availibility, name='check_availibility'),
    url(r'^booking/', booking_view, name='booking'),
    url(r'^contact_us/', contact_us, name='contact_us'),
    url(r'^review_create/', review_create, name='review_create'),
    url(r'^checkout/', payment_view, name='checkout'),
    url(r'^booking_success/', booking_success, name='booking_success'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^gallery/', gallery, name='gallery'),
    url(r'^booking_detail/', booking_detail, name='booking_detail'),
    url(r'^about/', about, name='about'),
    url(r'^blog/', blog, name='blog'),
    url(r'^faq/', faq, name='faq'),
    url(r'^room_detail/', room_detail, name='room_detail'),
    url(r'^room_detail1/', room_detail1, name='room_detail1'),
    url(r'^room_detail2/', room_detail2, name='room_detail2'),
    url(r'^room_detail3/', room_detail3, name='room_detail3'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app/urls.py
from django.conf.urls import url
from app.views import (home, login_view, register_view, 
                        logout_view, review_list, review_list1, 
                        review_list2, review_list3, review_list4,
                        booking_detail, booking_update, booking_delete, 
                        room_detail, room_detail1, room_detail2, 
                        room_detail3, about, gallery, 
                        blog, faq, check_availibility, 
                        room_details)

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^review_list/$', review_list, name='review_list'),
    url(r'^review_list/1star$', review_list1, name='review_list1'),
    url(r'^review_list/2star$', review_list2, name='review_list2'),
    url(r'^review_list/3star$', review_list3, name='review_list3'),
    url(r'^review_list/4star$', review_list4, name='review_list4'),
    url(r'^(?P<id>\d+)/$', booking_detail, name='booking_detail'),
  	url(r'^(?P<id>\d+)/update/$', booking_update, name='booking_update'),
  	url(r'^(?P<id>\d+)/delete/$', booking_delete, name='booking_delete'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^room_details/', room_details, name='room_details'),
    url(r'^room_detail1/', room_detail1, name='room_detail1'),
    url(r'^room_detail2/', room_detail2, name='room_detail2'),
    url(r'^room_detail3/', room_detail3, name='room_detail3'),
    url(r'^about/', about, name='about'),
    url(r'^gallery/', gallery, name='gallery'),
    url(r'^blog/', blog, name='blog'),
    url(r'^faq/', faq, name='faq'),
    url(r'^check_availibility/', check_availibility, name='check_availibility'),
]   

src/app/templates/about.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if IE 9]><html class="ie ie9"> <![endif]-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>P.G. Portal</title>
    
    <!-- Favicons-->
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="../static/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="../static/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="../static/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="../static/img/apple-touch-icon-144x144-precomposed.png">
    

    <!-- BASE CSS -->
    <!-- <link href="css/base.css" rel="stylesheet"> -->

    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >
<link rel="stylesheet" href="{% static 'css/menu.css' %}" />
<link rel="stylesheet" href="{% static 'css/base.css' %}" />
    
<link rel="stylesheet" type="text/css" href="{% static 'css/DateTimePicker.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">

<body>

    <!--[if lte IE 8]>
        <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a>.</p>
    <![endif]-->
    
     <div class="layer"></div>
    <!-- Mobile menu overlay mask -->
    
    <div id="preloader">
        <div data-loader="circle-side"></div>
    </div><!-- End Preload -->
    
    <!-- Header ================================================== -->
    <header>
    <div class="container">
        <div class="row">
            <div class="col--md-3 col-sm-3 col-xs-3">
                <a href="{% url 'app:home' %}" id="logo">
                <img src="../static/img/logo.png" width="190" height="23" alt="" data-retina="true">
                </a>
            </div>
            <nav class="col--md-9 col-sm-9 col-xs-9">
            <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="{% static 'js/javascript:void(0);' %}"><span>Menu mobile</span></a>
            
            <div class="main-menu">
                <div id="header_menu">
                     <img src="../static/img/logo_m.png" width="141" height="40" alt="" data-retina="true">
                </div>
                <a href="#" class="open_close" id="close_in"><i class="icon_set_1_icon-77"></i></a>
                 <ul>
                    <li class="submenu">
                    <a href="{% url 'app:home' %}">Home</a>
                    </li>
                   
                    <li class="submenu">
                    <a href="{% static 'js/javascript:void(0);' %}" class="show-submenu">Pages<i class="icon-down-open-mini"></i></a>
                    <ul>
                    	
                        <li><a href="/about">About us</a></li>
                        <li><a href="/faq">Faq</a></li>
                        <li><a href="/gallery">gallery</a></li>
                    </ul>
                    </li>
                    <li><a href="{% url 'check_availibility' %}">Check Availibility</a></li>
                     <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'contact_us' %}">Contact us</a></li>
                </ul>
            </div><!-- End main-menu -->
            
            </nav>
        </div><!-- End row -->
    </div><!-- End container -->
    </header>
    <!-- End Header =============================================== -->
    
    <!-- SubHeader =============================================== -->
    <section class="parallax-window" id="short" data-parallax="scroll" data-image-src="../static/img/sub_header_short_2.jpg" data-natural-width="1400" data-natural-height="350">
        <div id="subheader">
            <h1>Our Wonderfull Properties</h1>
    </div><!-- End subheader -->
    </section><!-- End section -->
    <!-- End SubHeader ============================================ -->
    
    <div class="container margin_60">
       <p class="lead styled">
            In this days students study further apartfrom their home or family. That's why, they live in hostel or in P. G. So, for that purpose we create this site to help them to find the room for to stay. You also choose your location too. What ever further facility you need you just tell us in the contact us page. You also select or choose your payment range. For your range you choose your room for P. G. You also contact your landlord too. 
        </p>
    	<div class="row about">
                <div class="col-md-5 col-sm-6 col-md-offset-1">
                   <h3>1* P.G.</h3>
                        <p>
                            In 1* P.G. we offered customers a basic facilities like furniture, cupboard, fan, table and chair etc. We love to help people through their P.G. so, if any user have any problem or query they can contact us or directly contact to the lanlord. 
                        </p>
                </div>
                <div class="col-md-4 col-sm-6 col-md-offset-1">
                <img src="../static/img/about_1.jpg" alt="" class="img-responsive styled"> 
                </div>
      </div><!-- End row -->
 		<div class="divider hidden-xs"></div>
       <div class="row about" >
            <div class="col-md-5 col-sm-6 col-md-offset-1 col-md-push-5">
                 <h3>3* P.G.</h3>
                        <p>
                            In 3* P.G. we gave a house or a flat to the customer. We also give it with the <strong>Extra Facilities </strong> which are :
                        </p>
                        <ul class="list_ok">
                            <li>Food</li>
                            <li>Laundry</li>
                             <li>Maid</li>
                        </ul>
            </div>
            <div class="col-md-4 col-sm-6 col-md-offset-1 col-md-pull-6">
               <img src="../static/img/about_2.jpg" alt="" class="img-responsive styled"> 
            </div>
        </div><!-- End row -->
      <div class="divider hidden-xs"></div>
        <div class="row about">
                <div class="col-md-5 col-sm-6 col-md-offset-1">
                   <h3>2* P.G.</h3>
                        <p>
                            In the 2* P.G. we give a small house like 1 BHK flat or house. A user can add facilities for their seek and can contact with a lanlord for more information or inquiry.
                        </p>
                </div>
                <div class="col-md-4 col-sm-6 col-md-offset-1">
                <img src="../static/img/about_3.png" alt="" class="img-responsive styled"> 
                </div>
      </div><!-- End row -->
    </div><!-- End container -->
    
   <section class="promo_full">
    <div class="promo_full_wp">
        <div>
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="carousel_testimonials">
                        
                            
                        </div><!-- End carousel_testimonials -->
                    </div><!-- End col-md-8 -->
                </div><!-- End row -->
            </div><!-- End container -->
        </div><!-- End promo_full_wp -->
    </div><!-- End promo_full -->
    </section><!-- End section -->   


     <footer >
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-12">
                    <img src="../static/img/logo_footer.png" width="141" height="40" alt="" id="logo_footer" data-retina="true">
					<ul id="contact_details_footer">
          				<li>Route de Sablet 1023, Marseille<br>France 01923</li>
                        <li><a href="tel://004542344599">+45 423 445 99</a> / <a href="#0"><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></a></li>
                    </ul>  
                </div>
                <div class="col-md-2 col-sm-4">
                    <h3>About</h3>
                    <ul>
                        <li><a href="/about">About us</a></li>
                        <li><a href="{% url 'contact_us' %}">Contact us</a></li>
                         <li><a href="/gallery">gallery</a></li>
                    </ul>
                </div>                
                <div class="col-md-3 col-sm-4">
                   
                </div>
                <div class="col-md-3 col-sm-4"  id="newsletter">
                    <h3>News letter</h3>
                    <p>Join our news letter to keep be informed about offers and news.</p>
					<div id="message-newsletter_2"></div>
						<form method="post" action="assets/newsletter.php" name="newsletter_2" id="newsletter_2">
                        <div class="form-group">
                            <input name="email_newsletter_2" id="email_newsletter_2"  type="email" value=""  placeholder="Your mail" class="form-control">
                          </div>
                            <input type="submit" value="Subscribe" class="btn_1 white" id="submit-newsletter_2">
                    	</form>
                </div>
            </div><!-- End row -->
            <div class="row">
                <div class="col-md-12">
                    <div id="social_footer">
                        <ul>
                            <li><a href="https://www.facebook.com/"><i class="icon-facebook"></i></a></li>
                            <li><a href="https://twitter.com/login?lang=en"><i class="icon-twitter"></i></a></li>
                            <li><a href="https://www.google.co.in/"><i class="icon-google"></i></a></li>
                            <li><a href="https://www.instagram.com/accounts/login/"><i class="icon-instagram"></i></a></li>
                            <li><a href="https://www.youtube.com/"><i class="icon-youtube-play"></i></a></li>
                        </ul>
                          <p>Copyright © 2018  |  All Right Reserved</p>

                    </div>
                </div>
            </div><!-- End row -->
        </div><!-- End container -->
    </footer><!-- End footer -->

<div id="toTop"></div><!-- Back to top button -->
   
    
<!-- COMMON SCRIPTS -->
<script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/common_scripts_min.js' %}"></script>
<script src="{% static 'js/validate.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>

</body>
</html>

src/app/templates/check_availibility.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
<br/><br/><br/><br/><br/>
{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
	<h1>Check Availibility</h1>
	<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
		{{ form|crispy }}
		<input type='submit' class='btn btn-default' value='Check Availibility' />
	</form>
</div>
{% endblock content %}

src/app/templates/form.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<div class='col-sm-6 col-sm-offset-4'>
<h1>{{ title }}</h1>
<hr/>

{% if title == 'Book Your Room' %}
	{% if request.user.is_authenticated %}
		<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
		{{ form|crispy }}
		<input type='submit' class='btn btn-default' value='{{ title }}' />
		</form>
		{% else %}
		<h3>You must login first</h3>
		<a href="/login" class='btn btn-default'>Login</a>
		{% endif %}
{% else %}
<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='{{ title }}' />
{% if title == 'Login' %}
<a href="/register" class='btn btn-default'>Sign Up</a>
{% endif %}
</form>
{% endif %}
</div>

{% endblock content %}

src/app/templates/index.html
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>P.G. Portal</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="../static/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="../static/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="../static/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="../static/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="../static/img/apple-touch-icon-144x144-precomposed.png">

    <!-- BASE CSS -->
    <!-- <link href="css/base.css" rel="stylesheet"> -->
    
    <!-- SPECIFIC CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
    
    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >
<link rel="stylesheet" href="{% static 'css/menu.css' %}" />
<link rel="stylesheet" href="{% static 'css/base.css' %}" />
    
<link rel="stylesheet" type="text/css" href="{% static 'css/DateTimePicker.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
</style>
<body>
<div class="layer"></div>
    <!-- Mobile menu overlay mask -->
    
    <div id="preloader">
        <div data-loader="circle-side"></div>
    </div><!-- End Preload -->    
<header>
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="row">
            <div class="col--md-3 col-sm-3 col-xs-3">
                <a href="{% url 'app:home' %}" id="logo">
                <img src="/static/img/logo.png" alt="" data-retina="true" width="190" height="23">
                </a>
            </div>
            <nav class="col--md-9 col-sm-9 col-xs-9">
            <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="{% static 'js/javascript:void(0);' %}"><span>Menu mobile</span></a>
            <div class="main-menu">
                <div id="header_menu">
                     <img src="/static/img/logo_m.png" width="141" height="40" alt="" data-retina="true">
                </div>
                <a href="#" class="open_close" id="close_in"><i class="icon_set_1_icon-77"></i></a>
                 <ul>
                    <li class="submenu">
                    <a href="{% url 'app:home' %}">Home</a>
                    </li>
                   
                    <li class="submenu">
                    <a href="{% static 'js/javascript:void(0);' %}" class="show-submenu">Pages<i class="icon-down-open-mini"></i></a>
                    <ul>
                        
                        <li><a href="/about">About us</a></li>
                        <li><a href="/faq">Faq</a></li>
                        <li><a href="/gallery">gallery</a></li>
                       </ul>
                    </li>
                    <li><a href="{% url 'check_availibility' %}">Check Availibility</a></li>
                    {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    {% else %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% endif %}
                    <li><a href="{% url 'contact_us' %}">Contact us</a></li>
                </ul>
            </div><!-- End main-menu -->
            
            </nav>
          <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> -->
            <!-- <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> -->
          <!-- </button> -->
          <!-- <a class="navbar-brand" href="{% url 'app:home' %}">PG Portal</a> -->
        <!-- </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'app:home' %}">Home</a></li>
            <li><a href="{% url 'booking' %}">Booking</a></li>
            <li><a href="{% url 'contact_us' %}">Contact Us</a></li>
            <li><a href="{% url 'app:review_list' %}">Reviews</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'register' %}">Register</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div> -->

    
    </div>
</nav>

</header>

    <!-- End SubHeader ============================================ -->
            
    <div class="container margin_60_35">
        {% block content %}{% endblock content %}
    </div><!-- End container -->
   
  
    <section class="promo_full">
    <div class="promo_full_wp">
        <div>
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="carousel_testimonials">
                        
                            
                        </div><!-- End carousel_testimonials -->
                    </div><!-- End col-md-8 -->
                </div><!-- End row -->
            </div><!-- End container -->
        </div><!-- End promo_full_wp -->
    </div><!-- End promo_full -->
    </section><!-- End section -->    
    
    
    
     <footer >
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-12">
                    <img src="/static/img/logo_footer.png" width="141" height="40" alt="" id="logo_footer" data-retina="true">
                    <ul id="contact_details_footer">
                        <li>Route de Sablet 1023, Marseille<br>France 01923</li>
                        <li><a href="tel://004542344599">+45 423 445 99</a> / <a href="#0"><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></a></li>
                    </ul>  
                </div>
                <div class="col-md-2 col-sm-4">
                    <h3>About</h3>
                    <ul>
                        <li><a href="/about">About us</a></li>
                        <li><a href="/contact_us">Contact us</a></li>
                        <li><a href="/gallery">gallery</a></li>
                    </ul>
                </div>                
                <div class="col-md-3 col-sm-4">
                   
                </div>
                <div class="col-md-3 col-sm-4"  id="newsletter">
                    <h3>News letter</h3>
                    <p>Join our news letter to keep be informed about offers and news.</p>
                    <div id="message-newsletter_2"></div>
                        <form method="post" action="assets/newsletter.php" name="newsletter_2" id="newsletter_2">
                        <div class="form-group">
                            <input name="email_newsletter_2" id="email_newsletter_2"  type="email" value=""  placeholder="Your mail" class="form-control">
                          </div>
                            <input type="submit" value="Subscribe" class="btn_1 white" id="submit-newsletter_2">
                        </form>
                </div>
            </div><!-- End row -->
            <div class="row">
                <div class="col-md-12">
                    <div id="social_footer">
                        <ul>
                            <li><a href="https://www.facebook.com/"><i class="icon-facebook"></i></a></li>
                            <li><a href="https://twitter.com/login?lang=en"><i class="icon-twitter"></i></a></li>
                            <li><a href="https://www.google.co.in/"><i class="icon-google"></i></a></li>
                            <li><a href="https://www.instagram.com/accounts/login/"><i class="icon-instagram"></i></a></li>
                            <li><a href="https://www.youtube.com/"><i class="icon-youtube-play"></i></a></li>
                        </ul>
                          <p>Copyright © 2018 <a target="_blank" title="Free CSS Themes" href="http://freecssthemes.com/"></a>  |  All Right Reserved</p>

                    </div>
                </div>
            </div><!-- End row -->
        </div><!-- End container -->
    </footer><!-- End footer -->

<div id="toTop"></div><!-- Back to top button -->
        
<!-- COMMON SCRIPTS -->
<script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/common_scripts_min.js' %}"></script>
<script src="{% static 'js/validate.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>

<script type="text/javascript" src="{% static 'js/DateTimePicker.js' %}"></script>
<script type="text/javascript">$("#dtBox").DateTimePicker();</script>
</body>
</html>

src/app/templates/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

src/app/templates/proceed_payment.html
{% extends 'index.html' %}

{% block content %}
<center><h2>Proceed to Payment:.</h2>
	<pre  style='width: fit-content;'>Total Booking Amount:	{{ price }}</pre>
<a href="/booking_success" class='btn btn-primary'>Pay</a>	
<a href="/{{ object.id }}/delete" class='btn btn-primary'>Cancel Booking</a>
{% endblock content %}

src/app/templates/submit_success.html
{% include "index.html" %}	

<!-- {% if title == 'Contact Us' %} -->
<center><h3>We will get back to you very shortly.</h3>
<a href="/" class='btn btn-primary'>Back to Home</a></center>
<!-- {% endif %} -->
{% if title == 'Book Your Room' %}
<center><h3>Congrats! Your room is Successfully booked.</h3>
<a href="/" class='btn btn-primary'>Back to Home</a></center>
{% endif %}